//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casa
    {
        public int idCasa { get; set; }
        public string tipodeCasa { get; set; }
        public string Ubicacion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Dueño { get; set; }
    
        public virtual Dueños Dueños { get; set; }
    }
}
